# Site settings
title: mathblogging.org
email: mathblogging.network@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Your one stop shop for mathematical blogs.
baseurl: "/"
url: "https://mathblogging.org" # the base hostname & protocol for your site
twitter_username: mathblogging
github_username:  mathblogging

# Build settings
markdown: kramdown
sass:
  style: compressed
